# grafana/provisioning/datasources/datasources.yaml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy                 # Use 'proxy' if Grafana should query Prometheus on behalf of the client
    url: http://prometheus:9090    # Prometheus URL (use service name if both in docker-compose)
    isDefault: true                # Set as the default data source
    editable: true                 # Allow the data source to be edited via Grafana UI
    jsonData:
      httpMethod: POST             # Use POST requests for queries
